# tomcat.yml - This include file installs Apache Tomcat 7 and uploads the user
# file.
---
- name: install tomcat7
  apt:
    name: tomcat7
    state: present
  become: yes

- name: install tomcat7-docs
  apt:
    name: tomcat7-docs
    state: present
  become: yes

- name: install tomcat7-admin
  apt:
    name: tomcat7-admin
    state: present
  become: yes

- name: copy tomcat-users.xml over
  copy:
    src: ../files/tomcat-users.xml
    dest: /etc/tomcat7/tomcat-users.xml
    owner: root
    group: tomcat7
    mode: 0644
  become: yes

- name: restart tomcat
  service:
    name: tomcat7
    state: restarted
  become: yes

- name: ensure tomcat starts on boot
  service:
    name: tomcat7
    enabled: yes
  become: yes
