# vsftpd.yml - This include file sets up the vulnerable vsftpd installation.
---
- name: make sure dns is configured
  raw: echo "nameserver {{ nameserver_ip }}" > /etc/resolv.conf
  become: yes

- name: install git
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: clone git repo containing backdoored vsftpd
  git:
    repo: "https://www.github.com/nikdubois/vsftpd-2.3.4-infected.git"
    dest: /tmp/vsftpd-2.3.4-infected

- name: get build dependencies for vsftpd
  command: apt-get -y build-dep vsftpd
  become: yes

# There are a few gotchas in the build on Ubuntu 12.04. These steps resolve
# them.

- name: Modify LIBS arg in MAKEFILE to link pam and cap modules
  replace:
    path: /tmp/vsftpd-2.3.4-infected/Makefile
    regexp: 'LIBS(.*)=(.*)`.\/vsf_findlibs\.sh`'
    replace: 'LIBS = `./vsf_findlibs.sh` -lpam -lcap'

- name: make vsf_findlibs.sh executable
  file:
    path: /tmp/vsftpd-2.3.4-infected/vsf_findlibs.sh
    mode: "u+x,g+x,o+x"

- name: symlink libcap.so to /lib64
  file:
    src: /lib/x86_64-linux-gnu/libcap.so
    dest: /lib64/libcap.so
    state: link
  become: yes

- name: build vsftpd
  make:
    chdir: /tmp/vsftpd-2.3.4-infected

- name: create /usr/local/man/man5 directory
  file:
    path: /usr/local/man/man5
    state: directory
  become: yes

- name: create /usr/local/man/man8 directory
  file:
    path: /usr/local/man/man8
    state: directory
  become: yes

- name: make install
  make:
    chdir: /tmp/vsftpd-2.3.4-infected
    target: install
  become: yes

# This makes it easier to run vsftpd as a daemon.

- name: copy sysv init script
  copy:
    src: ../files/vsftpd.rc
    dest: /etc/init.d/vsftpd
    owner: root
    group: root
    mode: 0733
  become: yes

- name: copy vsftpd.conf
  copy:
    src: ../files/vsftpd.conf
    dest: /etc/vsftpd.conf
    owner: root
    group: root
  become: yes

- name: create ftp user
  user:
    name: ftp
    home: /
    state: present
  become: yes

- name: start vsftpd
  service:
    name: vsftpd
    state: started
  become: yes

- name: enable vsftpd
  service:
    name: vsftpd
    enabled: yes
  become: yes

- name: change hostname
  hostname:
    name: fs
  become: yes

- name: delete files from /tmp
  file:
    path: /tmp/vsftpd-2.3.4-infected/
    state: absent

- name: make files directory
  file:
    path: /files
    mode: 0755
    owner: root
    group: root
    state: directory
  become: yes

# The VulnServer is used during the exploit dev portion of the camp.

- name: clone vulnserver into /files
  git:
    repo: https://github.com/stephenbradshaw/vulnserver
    dest: /files/vulnserver
  become: yes
