# main.yml - Sets up the Windows systems by adding the hospital users and
# updating the DNS config.
---
- name: upload csv
  win_copy:
    src: ../files/user-create.csv
    dest: C:\user-create.csv

- name: run script
  script: ../files/Add-Users.ps1

- name: delete csv
  win_file:
    path: C:\user-create.csv
    state: absent

- name: enable rdp
  win_regedit:
    path: 'hklm:\system\currentcontrolset\control\terminal server'
    name: fDenyTSConnections 
    type: dword 
    data: 0

- name: allow remote admin through firewall
  win_shell: "netsh firewall set service remoteadmin enable"

- name: allow rdp through firewall
  win_shell: "netsh firewall set service remotedesktop enable"

- include: update-dns.yml
