# update-dns.yml - This include file modifies a host's DNS configuration to
# point at the IP specified in the inventory file.
---
- name: update DNS config
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ nameserver_ip }}"
