# main.yml - Promote Administrator accounts for the management department.
---
- name: promote floor manager
  win_user:
    name: fflinch
    groups: Administrators
    groups_action: add

- name: promote management user
  win_user:
    name: mgmtadmin
    groups: Administrators
    groups_action: add
