# main.yml - The main playbook to build the nameserver role.
#
# This playbook assumes that the system it is being run against is a CentOS 7
# system. This playbook uses become, so it must be run with the -K flag.

- name: install named
  yum:
    name: bind
    state: latest
  become: true

- name: copy config files over
  copy:
    src: ../files/
    dest: /etc
    owner: root
    group: named
  become: true

- name: relocate db file to /var/named
  command: mv /etc/db.metropolis-general.com /var/named/
  become: true

- name: start named if it's not already started
  systemd:
    name: named
    state: started
  become: true

- name: enable named so it comes up on boot
  systemd:
    name: named
    state: enabled
  become: true

- name: add iptables rule for DNS traffic
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    jump: ACCEPT
    comment: dns for named
  become: yes
