# bash.yml - Compile bash 4.1, which is vulnerable to shellshock, and replace
# the standard version of bash with this older version.
# This playbook must be run with the -K flag.
---
- name: download and unpack bash source
  unarchive:
    src: http://ftpmirror.gnu.org/gnu/bash/bash-4.1.tar.gz
    dest: /tmp
    remote_src: True

- name: run configure script
  raw: cd /tmp/bash-4.1 && ./configure

- name: build bash-4.1
  make:
    chdir: /tmp/bash-4.1

- name: uninstall current version of bash
  raw: echo "Yes, do as I say!" | apt-get remove bash
  become: yes

- name: install bash-4.1
  raw: cd /tmp/bash-4.1 && make install
  become: yes

- name: symlink at /usr/bin/bash
  file:
    src: /usr/local/bin/bash
    dest: /usr/bin/bash
    state: link
  become: yes

- name: symlink at /bin/bash
  file:
    src: /usr/local/bin/bash
    dest: /bin/bash
    state: link
  become: yes

- name: switch shell to bash for root
  user:
    name: root
    shell: /bin/bash
  become: yes

- name: switch shell to bash for mgmtadmin
  user:
    name: mgmtadmin
    shell: /bin/bash
  become: yes
