# main.yml - Performs the Postfix, Horde, and Shellshock-vulnerable
# bash installations.
# This playbook requires the -K flag. This playbook is designed
# to be run against a system with Debian 8 installed on it.
# This playbook also requires that a shell other than bash be set for the user
# on the remote system. Ansible really doesn't like it when you uninstall bash
# midway through a play if it's using it, and this is necessary in order
# to properly install the vulnerable version of bash. The shell used for
# testing was sh, so in theory it should work in any other modern shell, but
# YMMV.
# Finally, this playbook takes a really long time to run because of the Horde
# installations. Normal execution time is ~14 minutes.
---
- include: postfix.yml
- include: procmail.yml
- include: bash.yml
- include: courier.yml
- include: horde.yml
